##################
### AUTO START ###
##################

# exec-once = {x}

exec-once = waybar &
exec-once = hyprlock &
exec-once = swaync &
exec-once = blueman-applet &
exec-once = awww-daemon &
exec-onee = hypridle &
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = kdeconnectd &
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
