source = ~/.config/hypr/look/colors.conf

# Wrap raw hex values into proper rgba format
$col_primary           = rgba($primary ff)
$col_on_primary        = rgba($on_primary ff)
$col_primary_container = rgba($primary_container ff)
$col_secondary         = rgba($secondary ff)
$col_background        = rgba($background ff)
$col_surface           = rgba($surface ff)
$col_outline           = rgba($outline ff)
$col_shadow            = rgba($shadow ff)
$col_surface_dim       = rgba($surface_dim ff)
$col_outline_variant   = rgba($outline_variant ff)
# add more as needed...
