# vim:ft=kitty

## name:     Gruvbox-Light
## author:   morhetz (https://github.com/morhetz)
## license:  MIT
## upstream: https://github.com/morhetz/gruvbox
## blurb:    Retro groove color scheme for the terminal! (Light variant)



# The basic colors
foreground              #3C3836
background              #FBF1C7
selection_foreground    #FBF1C7
selection_background    #7C6F64

# Cursor colors
cursor                  #3C3836
cursor_text_color       #FBF1C7

# URL underline color when hovering with mouse
url_color               #076678

# Kitty window border colors
active_border_color     #7C6F64
inactive_border_color   #D5C4A1
bell_border_color       #B57614

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F9F5D7
active_tab_background   #B57614
inactive_tab_foreground #3C3836
inactive_tab_background #EBDBB2
tab_bar_background      #F9F5D7

# Colors for marks (marked text in the terminal)
mark1_foreground #FBF1C7
mark1_background #7C6F64
mark2_foreground #FBF1C7
mark2_background #B57614
mark3_foreground #FBF1C7
mark3_background #076678

# The 16 terminal colors

# black
color0 #FBF1C7
color8 #928374

# red
color1 #CC241D
color9 #9D0006

# green
color2  #98971A
color10 #79740E

# yellow
color3  #D79921
color11 #B57614

# blue
color4  #458588
color12 #076678

# magenta
color5  #B16286
color13 #8F3F71

# cyan
color6  #689D6A
color14 #427B58

# white
color7  #7C6F64
color15 #3C3836
