# vim:ft=kitty

## name:     Kanagawa-Light (Lotus)
## author:   rebelot (https://github.com/rebelot)
## license:  MIT
## upstream: https://github.com/rebelot/kanagawa.nvim
## blurb:    NeoVim dark colorscheme inspired by the colors of the famous painting by Katsushika Hokusai. (Lotus/Light variant)



# The basic colors
foreground              #545464
background              #F2ECBC
selection_foreground    #F2ECBC
selection_background    #8A8980

# Cursor colors
cursor                  #545464
cursor_text_color       #F2ECBC

# URL underline color when hovering with mouse
url_color               #597B75

# Kitty window border colors
active_border_color     #4D699B
inactive_border_color   #DCD5AC
bell_border_color       #CC6D00

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F2ECBC
active_tab_background   #4D699B
inactive_tab_foreground #545464
inactive_tab_background #E5DDB0
tab_bar_background      #DCD5AC

# Colors for marks (marked text in the terminal)
mark1_foreground #F2ECBC
mark1_background #8A8980
mark2_foreground #F2ECBC
mark2_background #CC6D00
mark3_foreground #F2ECBC
mark3_background #597B75

# The 16 terminal colors

# black
color0 #D5CEA3
color8 #8A8980

# red
color1 #C84053
color9 #D7474B

# green
color2  #6F894E
color10 #6E915F

# yellow
color3  #77713F
color11 #836F4A

# blue
color4  #4D699B
color12 #6693BF

# magenta
color5  #624C83
color13 #624C83

# cyan
color6  #597B75
color14 #5E857A

# white
color7  #545464
color15 #43436C
