# vim:ft=kitty

## name:     Rosé Pine Dawn
## author:   Rosé Pine (https://github.com/rose-pine)
## license:  MIT
## upstream: https://github.com/rose-pine/rose-pine-theme
## blurb:    All natural pine, faux fur and a bit of soothingly muted purples. (Dawn variant)



# The basic colors
foreground              #575279
background              #faf4ed
selection_foreground    #faf4ed
selection_background    #cecacd

# Cursor colors
cursor                  #575279
cursor_text_color       #faf4ed

# URL underline color when hovering with mouse
url_color               #56949f

# Kitty window border colors
active_border_color     #797593
inactive_border_color   #dfd8c8
bell_border_color       #ea9d34

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #faf4ed
active_tab_background   #907aa9
inactive_tab_foreground #575279
inactive_tab_background #f2e9de
tab_bar_background      #dfd8c8

# Colors for marks (marked text in the terminal)
mark1_foreground #faf4ed
mark1_background #9893a5
mark2_foreground #faf4ed
mark2_background #ea9d34
mark3_foreground #faf4ed
mark3_background #56949f

# The 16 terminal colors

# black
color0 #f2e9de
color8 #9893a5

# red
color1 #b4637a
color9 #b4637a

# green
color2  #286983
color10 #286983

# yellow
color3  #ea9d34
color11 #ea9d34

# blue
color4  #56949f
color12 #56949f

# magenta
color5  #907aa9
color13 #907aa9

# cyan
color6  #d7827e
color14 #d7827e

# white
color7  #797593
color15 #575279
