# vim:ft=kitty

## name:     Solarized-Dark
## author:   Ethan Schoonover (https://ethanschoonover.com)
## license:  MIT
## upstream: https://github.com/altercation/solarized
## blurb:    Precision colors for machines and people.



# The basic colors
foreground              #839496
background              #002B36
selection_foreground    #002B36
selection_background    #839496

# Cursor colors
cursor                  #839496
cursor_text_color       #002B36

# URL underline color when hovering with mouse
url_color               #2AA198

# Kitty window border colors
active_border_color     #268BD2
inactive_border_color   #073642
bell_border_color       #B58900

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #002B36
active_tab_background   #268BD2
inactive_tab_foreground #839496
inactive_tab_background #073642
tab_bar_background      #001E27

# Colors for marks (marked text in the terminal)
mark1_foreground #002B36
mark1_background #586E75
mark2_foreground #002B36
mark2_background #B58900
mark3_foreground #002B36
mark3_background #2AA198

# The 16 terminal colors

# black
color0 #073642
color8 #002B36

# red
color1 #DC322F
color9 #CB4B16

# green
color2  #859900
color10 #586E75

# yellow
color3  #B58900
color11 #657B83

# blue
color4  #268BD2
color12 #839496

# magenta
color5  #6C71C4
color13 #6C71C4

# cyan
color6  #2AA198
color14 #93A1A1

# white
color7  #839496
color15 #FDF6E3
