# vim:ft=kitty

## name:     Tokyo Night
## author:   enkia (https://github.com/enkia)
## license:  MIT
## upstream: https://github.com/enkia/tokyo-night-vscode-theme
## blurb:    A clean, dark Visual Studio Code theme that celebrates the lights of downtown Tokyo at night.



# The basic colors
foreground              #c0caf5
background              #1a1b2e
selection_foreground    #1a1b2e
selection_background    #364a82

# Cursor colors
cursor                  #c0caf5
cursor_text_color       #1a1b2e

# URL underline color when hovering with mouse
url_color               #7dcfff

# Kitty window border colors
active_border_color     #7aa2f7
inactive_border_color   #24283b
bell_border_color       #e0af68

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1a1b2e
active_tab_background   #7aa2f7
inactive_tab_foreground #c0caf5
inactive_tab_background #1f2335
tab_bar_background      #13141f

# Colors for marks (marked text in the terminal)
mark1_foreground #1a1b2e
mark1_background #565f89
mark2_foreground #1a1b2e
mark2_background #e0af68
mark3_foreground #1a1b2e
mark3_background #7dcfff

# The 16 terminal colors

# black
color0 #15161e
color8 #414868

# red
color1 #f7768e
color9 #f7768e

# green
color2  #9ece6a
color10 #9ece6a

# yellow
color3  #e0af68
color11 #e0af68

# blue
color4  #7aa2f7
color12 #7aa2f7

# magenta
color5  #bb9af7
color13 #bb9af7

# cyan
color6  #7dcfff
color14 #7dcfff

# white
color7  #a9b1d6
color15 #c0caf5
